<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student [
    <!ELEMENT student (#PCDATA|name|class|age|section|quality)*>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT section (#PCDATA)>
    <!ELEMENT quality (#PCDATA)>
]>
<student>
    <name>malware</name>
    <name>2</name>
    <class>11</class>
    <age>almost 18</age>
    <section>a</section>
    <section>A</section>
    <section>A1</section>

    <quality>Premium</quality>
    <quality>Premium</quality>
    <quality>Premium</quality>
    <quality>Premium</quality>
    <quality>Premium</quality>

</student>